---
language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
- pip install flake8
- python setup.py install

jobs:
  include:
    - stage: test
      name: "Check for pep8 style"
      python: "3.7"
      script: flake8 aurblobs/
    - stage: build
      name: "Check if aurblobs builds"
      script: aurblobs

notifications:
  email: false
